dist: trusty
language: node_js
cache: yarn
node_js:
- '8.9.0'
before_install:
# Required due to: https://github.com/travis-ci/travis-ci/issues/7951
- curl -sSfL https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install --frozen-lockfile
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn lint
- yarn test # the prepare script already does a build prior to this
